---
title: "MDS Analysis of Semantic Variables"
output:
  html_document:
    author: "Magali Lopez Cortez"
    date: "`r format(Sys.time(), '%d %B, %Y')`"
    df_print: paged
    toc: yes
  pdf_document:
    toc: yes
---

```{r "setup", include=FALSE}
#Set working directory, load required packages
#library(RColorBrewer)
library(rdist)
library(ggrepel)
library(ggiraph) 
library(anchors) # for replace.values
library(car)
library(tidyverse)
library(broom)
library(superheat)
require("knitr")
```

```{r}
#Import dataset with semantic dimensions 
semdimDF <- read_csv("../QP_Data/Tilbe_dimensions.csv", col_types = cols(
  ROOT = col_factor(),
  Support = col_number(),
  Leaning = col_number(),
  Suspension = col_number(),
  Blockage.of.motion = col_number(),
  Orientation.in.vertical = col_number(),
  Dispersion = col_number(),
  Configuration.of.parts = col_number(),
  Configuration.wrt.Ground= col_number(),
  Containment = col_number(),
  Length.of.vertical.dimension = col_number(),
  Animate = col_number(),
  Inanimate = col_number(),
  Numerosity = col_number(),
  Material.properties.specified = col_number(),
  Potential.energy = col_number(),
  Contact = col_number()
  ))

semdimDF <- replace.value(semdimDF, c("Support","Leaning","Suspension","Blockage.of.motion","Orientation.in.vertical",
                                       "Dispersion", "Configuration.of.parts", "Configuration.wrt.Ground", "Containment",
                                       "Length.of.vertical.dimension", "Animate", "Inanimate", "Numerosity", 
                                       "Material.properties.specified", "Potential.energy", "Contact"), from=NA, to=as.integer(2))
# semdimDF <- mutate(semdimDF,
#   Support = as.factor(semdimDF$Support),
#   Leaning = as.factor(semdimDF$Leaning),
#   Suspension = as.factor(semdimDF$Suspension),
#   Blockage.of.motion = as.factor(semdimDF$Blockage.of.motion),
#   Orientation.in.vertical = as.factor(semdimDF$Orientation.in.vertical),
#   Dispersion = as.factor(semdimDF$Dispersion),
#   Configuration.of.parts = as.factor(semdimDF$Configuration.of.parts),
#   Configuration.wrt.Ground = as.factor(semdimDF$Configuration.wrt.Ground),
#   Containment = as.factor(semdimDF$Containment),
#   Length.of.vertical.dimension = as.factor(semdimDF$Length.of.vertical.dimension),
#   Animate = as.factor(semdimDF$Animate),
#   Inanimate = as.factor(semdimDF$Inanimate),
#   Numerosity = as.factor(semdimDF$Numerosity),
#   Material.properties.specified = as.factor(semdimDF$Material.properties.specified),
#   Potential.energy = as.factor(semdimDF$Potential.energy),
#   Contact = as.factor(semdimDF$Contact)
#   )

summary(semdimDF)
```

```{r, include=FALSE}
# Calculate distance matrix for Semantic Dimenions dataset using Hamming distance
semsimDF_root <- semdimDF$ROOT
semdimDF <- subset(semdimDF, select = -c(ROOT))

dm_ham <- rdist(semdimDF, metric="hamming")

fit_ham <- cmdscale(dm_ham,eig=TRUE, k=3) 
 
# Calculate variation and make scree plot
var_ham <- round(fit_ham$eig/sum(fit_ham$eig)*100, 1)
plot(fit_ham$eig/sum(fit_ham$eig), xlab="Dimensions", ylab="Proportion of variance")
 
# Create data frame with 
solution_ham <- data.frame("Dimension.1"=fit_ham$points[,1],
                        "Dimension.2"=fit_ham$points[,2],
                        "Dimension.3"=fit_ham$points[,3],
                        "Root" = semsimdf_root)
 
# Plot Dimensions 1 and 2
ggplot(data=solution_ham, aes(x=Dimension.1, y=Dimension.2, label=Root)) +
  geom_text() +
  #geom_text_repel() +
  theme_bw() +
  xlab(paste("Dim1 - ", var_ham[1], "%", sep="")) +
  ylab(paste("Dim2 - ", var_ham[2], "%", sep="")) +
  ggtitle("MDS plot")


# Plot Dimensions 2 and 3
ggplot(data=solution_ham, aes(x=Dimension.2, y=Dimension.3, label=Root)) +
  geom_text() +
  #geom_text_repel() +
  theme_bw() +
  xlab(paste("Dim2 - ", var_ham[2], "%", sep="")) +
  ylab(paste("Dim3 - ", var_ham[3], "%", sep="")) +
  ggtitle("MDS plot")

# Plot Dimensions 1 and 3
ggplot(data=solution_ham, aes(x=Dimension.1, y=Dimension.3, label=Root)) +
  geom_text() +
  #geom_text_repel() +
  theme_bw() +
  xlab(paste("Dim1 - ", var_ham[1], "%", sep="")) +
  ylab(paste("Dim3 - ", var_ham[3], "%", sep="")) +
  ggtitle("MDS plot")

```


```{r}

# Boxplots Dim1 ~ .Semantic variables

# Prepare canvas
par(mfrow=c(3,6))

# Check correlation between Dim1 and Animate
boxplot(solution_ham$Dimension.1 ~ semdimDF$Animate, ylab = "Dim 1", xlab = "Animate")
#summary(lm(Dimension.1 ~ Animate, data = both))

# Check correlation between Dim1 and Support
boxplot(solution_ham$Dimension.1 ~ semdimDF$Support, ylab = "Dim 1", xlab = "Support")
#summary(lm(formula = Dimension.1 ~ Support, data = both))

# Check correlation between Dim1 and Leaning
boxplot(solution_ham$Dimension.1 ~ semdimDF$Leaning, ylab = "Dim 1", xlab = "Leaning")
#summary(lm(formula = Dimension.1 ~ Leaning, data = both))

# Check correlation between Dim1 and Suspension
boxplot(solution_ham$Dimension.1 ~ semdimDF$Suspension, ylab = "Dim 1", xlab = "Suspension")
#summary(lm(formula = Dimension.1 ~ Suspension, data = both))

# Check correlation between Dim1 and Blockage of motion
boxplot(solution_ham$Dimension.1 ~ semdimDF$Blockage.of.motion, ylab = "Dim 1", xlab = "Blockage of motion")
#summary(lm(formula = Dimension.1 ~ Blockage.of.motion, data = both))

# Check correlation between Dim1 and Orientation in vertical
boxplot(solution_ham$Dimension.1 ~ semdimDF$Orientation.in.vertical, ylab = "Dim 1", xlab = "Orientation in vert")
#summary(lm(formula = Dimension.1 ~ Orientation.in.vertical, data = both))

# Check correlation between Dim1 and Dispersion
boxplot(solution_ham$Dimension.1 ~ semdimDF$Dispersion, ylab = "Dim 1", xlab = "Dispersion")
#summary(lm(formula = Dimension.1 ~ Dispersion, data = both))

# Check correlation between Dim1 and Configuartion of parts
boxplot(solution_ham$Dimension.1 ~ semdimDF$Configuration.of.parts, ylab = "Dim 1", xlab = "Config. of parts")
#summary(lm(formula = Dimension.1 ~ Configuration.of.parts, data = both))

# Check correlation between Dim1 and Configuration wrt Ground
boxplot(solution_ham$Dimension.1 ~ semdimDF$Configuration.wrt.Ground, ylab = "Dim 1", xlab = "Config. wrt ground")
#summary(lm(formula = Dimension.1 ~ Configuration.wrt.Ground, data = both))

# Check correlation between Dim1 and Containment
boxplot(solution_ham$Dimension.1 ~ semdimDF$Containment, ylab = "Dim 1", xlab = "Containment")
#summary(lm(formula = Dimension.1 ~ Containment, data = both))

# Check correlation between Dim1 and Length of vertical dimension
boxplot(solution_ham$Dimension.1 ~ semdimDF$Length.of.vertical.dimension, ylab = "Dim 1", xlab = "Length of vert dim")
#summary(lm(formula = Dimension.1 ~ Length.of.vertical.dimension, data = both))

# Check correlation between Dim1 and Inanimate
boxplot(solution_ham$Dimension.1 ~ semdimDF$Inanimate, ylab = "Dim 1", xlab = "Inanimate")
#summary(lm(formula = Dimension.1 ~ Inanimate, data = both))

# Check correlation between Dim1 and Numerosity
boxplot(solution_ham$Dimension.1 ~ semdimDF$Numerosity, ylab = "Dim 1", xlab = "Numerosity")
#summary(lm(formula = Dimension.1 ~ Numerosity, data = both))

# Check correlation between Dim1 and Material properties specified
boxplot(solution_ham$Dimension.1 ~ semdimDF$Material.properties.specified, ylab = "Dim 1", xlab = "Material properties spec")
#summary(lm(Dimension.1 ~ Material.properties.specified, data = both))

# Check correlation between Dim1 and Potential energy
boxplot(solution_ham$Dimension.1 ~ semdimDF$Potential.energy, ylab = "Dim 1", xlab = "Potential energy")
#summary(lm(formula = Dimension.1 ~ Potential.energy, data = both))

# Check correlation between Dim1 and Contact
boxplot(solution_ham$Dimension.1 ~ semdimDF$Contact, ylab = "Dim 1", xlab = "Contact")
#summary(lm(formula = Dimension.1 ~ Contact, data = both))
```
```{r}
# Boxplots Dim2 ~ .Semantic variables

# Prepare canvas
par(mfrow=c(3,6))

# Check correlation between Dim2 and Animate
boxplot(solution_ham$Dimension.2 ~ semdimDF$Animate, ylab = "Dim 2", xlab = "Animate")
#summary(lm(formula = Dimension.2 ~ Animate, data = both))

# Check correlation between Dim2 and Support
boxplot(solution_ham$Dimension.2 ~ semdimDF$Support, ylab = "Dim 2", xlab = "Support")
#summary(lm(formula = Dimension.2 ~ Support, data = both))

# Check correlation between Dim2 and Leaning
boxplot(solution_ham$Dimension.2 ~ semdimDF$Leaning, ylab = "Dim 2", xlab = "Leaning")
#summary(lm(formula = Dimension.2 ~ Leaning, data = both))

# Check correlation between Dim2 and Suspension
boxplot(solution_ham$Dimension.2 ~ semdimDF$Suspension, ylab = "Dim 2", xlab = "Suspension")
#summary(lm(Dimension.2 ~ Suspension, data = both))

# Check correlation between Dim2 and Blockage of motion
boxplot(solution_ham$Dimension.2 ~ semdimDF$Blockage.of.motion, ylab = "Dim 2", xlab = "Blockage of motion")
#summary(lm(formula = Dimension.2 ~ Blockage.of.motion, data = both))

# Check correlation between Dim2 and Orientation in vertical
boxplot(solution_ham$Dimension.2 ~ semdimDF$Orientation.in.vertical, ylab = "Dim 2", xlab = "Orientation in vert")
#summary(lm(formula = Dimension.2 ~ Orientation.in.vertical, data = both))

# Check correlation between Dim2 and Dispersion
boxplot(solution_ham$Dimension.2 ~ semdimDF$Dispersion, ylab = "Dim 2", xlab = "Dispersion")
#summary(lm(formula = Dimension.2 ~ Dispersion, data = both))

# Check correlation between Dim2 and Configuartion of parts
boxplot(solution_ham$Dimension.2 ~ semdimDF$Configuration.of.parts, ylab = "Dim 2", xlab = "Config. of parts")
#summary(lm(formula = Dimension.2 ~ Configuration.of.parts, data = both))

# Check correlation between Dim2 and Configuration wrt Ground
boxplot(solution_ham$Dimension.2 ~ semdimDF$Configuration.wrt.Ground, ylab = "Dim 2", xlab = "Config. wrt ground")
#summary(lm(formula = Dimension.2 ~ Configuration.wrt.Ground, data = both))

# Check correlation between Dim2 and Containment
boxplot(solution_ham$Dimension.2 ~ semdimDF$Containment, ylab = "Dim 2", xlab = "Containment")
#summary(lm(formula = Dimension.2 ~ Containment, data = both))

# Check correlation between Dim2 and Length of vertical dimension
boxplot(solution_ham$Dimension.2 ~ semdimDF$Length.of.vertical.dimension, ylab = "Dim 2", xlab = "Length of vert dim")
#summary(lm(formula = Dimension.2 ~ Length.of.vertical.dimension, data = both))

# Check correlation between Dim2 and Inanimate
boxplot(solution_ham$Dimension.2 ~ semdimDF$Inanimate, ylab = "Dim 2", xlab = "Inanimate")
#summary(lm(formula = Dimension.2 ~ Inanimate, data = both))

# Check correlation between Dim2 and Numerosity
boxplot(solution_ham$Dimension.2 ~ semdimDF$Numerosity, ylab = "Dim 2", xlab = "Numerosity")
#summary(lm(formula = Dimension.2 ~ Numerosity, data = both))

# Check correlation between Dim2 and Material properties specified
boxplot(solution_ham$Dimension.2 ~ semdimDF$Material.properties.specified, ylab = "Dim 2", xlab = "Material properties spec")
#summary(lm(formula = Dimension.2 ~ Material.properties.specified, data = both))

# Check correlation between Dim2 and Potential energy
boxplot(solution_ham$Dimension.2 ~ semdimDF$Potential.energy, ylab = "Dim 2", xlab = "Potential energy")
#summary(lm(formula = Dimension.2 ~ Potential.energy, data = both))

# Check correlation between Dim2 and Contact
boxplot(solution_ham$Dimension.2 ~ semdimDF$Contact, ylab = "Dim 2", xlab = "Contact")
#summary(lm(formula = Dimension.2 ~ Contact, data = both))
```
  
  